//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWork.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string MemberId { get; set; }
        public string AccountNumber { get; set; }
        public string Nickname { get; set; }
        public string Sequence { get; set; }
    }
}
