//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWork.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Type { get; set; }
        public string MemberId { get; set; }
        public string AccountNumber { get; set; }
        public bool Success { get; set; }
        public string Message { get; set; }
    }
}
